version: '2.4'
services:
  executor:
    container_name: executor
    image: 'us-central1-docker.pkg.dev/sourcegraph-ci/rfc795-internal/executor:5.4.5071@sha256:75a26481f28ef1e21c77c2fbec0edf8ad1b831065aafdd0ad27ff4b1a87ac2d7'
    cpus: 1
    mem_limit: '4g'
    # Run as root (required for docker daemon control)
    user: root
    # Run with privileged capabilities (required for docker daemon control)
    privileged: true
    environment:
      # Refer to https://docs.sourcegraph.com/admin/executors/deploy_executors_binary#step-2-setup-environment-variables on how to populate these variables
      - EXECUTOR_FRONTEND_URL=http://sourcegraph-frontend-0:3080
      # Note: Must match `executors.accessToken` in site config
      - EXECUTOR_FRONTEND_PASSWORD=
      # Choose what work to process
      - EXECUTOR_QUEUE_NAME=
      # Note: Must match left-hand side of scratch volume mount
      - EXECUTOR_DOCKER_HOST_MOUNT_PATH=/scratch
      # Note: Must match right-hand side of scratch volume mount
      - TMPDIR=/scratch
      # Run as root (required for docker daemon control)
      - UID=1000
      - GID=1000
    volumes:
      # Mount docker socket
      - '/var/run/docker.sock:/var/run/docker.sock'
      # Mount volume for workspaces shared by executor and launched containers
      - '/scratch:/scratch'
    networks:
      - sourcegraph
    restart: always
