version: '2.4'
services:
  migrator:
    environment:
      - PGHOST=${MAIN_PGHOST}
      - PGPASSWORD=${MAIN_PGPASSWORD}
      - CODEINTEL_PGHOST=${CODEINTEL_PGHOST}
      - CODEINTEL_PGPASSWORD=${CODEINTEL_PGPASSWORD}
      - CODEINSIGHTS_PGHOST=${CODEINSIGHTS_PGHOST}
      - CODEINSIGHTS_PGUSER=${CODEINSIGHTS_PGUSER}
      - CODEINSIGHTS_PGPASSWORD=${CODEINSIGHTS_PGPASSWORD}
  sourcegraph-frontend-0:
    environment:
      - PGHOST=${MAIN_PGHOST}
      - PGPASSWORD=${MAIN_PGPASSWORD}
      - CODEINTEL_PGHOST=${CODEINTEL_PGHOST}
      - CODEINSIGHTS_PGDATASOURCE=${CODEINSIGHTS_PGDATASOURCE}
      - REDIS_STORE_ENDPOINT=${REDIS_STORE_ENDPOINT}
      - REDIS_CACHE_ENDPOINT=${REDIS_CACHE_ENDPOINT}
  sourcegraph-frontend-internal:
    environment:
      - PGHOST=${MAIN_PGHOST}
      - PGPASSWORD=${MAIN_PGPASSWORD}
      - CODEINTEL_PGHOST=${CODEINTEL_PGHOST}
      - CODEINSIGHTS_PGDATASOURCE=${CODEINSIGHTS_PGDATASOURCE}
      - REDIS_STORE_ENDPOINT=${REDIS_STORE_ENDPOINT}
      - REDIS_CACHE_ENDPOINT=${REDIS_CACHE_ENDPOINT}
