version: '2.4'
services:
  migrator:
    environment:
      - PGHOST=${MAIN_PGHOST:-pgsql}
      - PGPASSWORD=${MAIN_PGPASSWORD:-sg}

      - CODEINTEL_PGHOST=${CODEINTEL_PGHOST:-codeintel-db}
      - CODEINTEL_PGPASSWORD=${CODEINTEL_PGPASSWORD:-sg}

      - CODEINSIGHTS_PGHOST=${CODEINSIGHTS_PGHOST:-codeinsights-db}
      - CODEINSIGHTS_PGUSER=${CODEINSIGHTS_PGUSER:-postgres}
      - CODEINSIGHTS_PGPASSWORD=${CODEINSIGHTS_PGPASSWORD:-password}
      - CODEINSIGHTS_PGDATASOURCE=${CODEINSIGHTS_PGDATASOURCE:-postgres://postgres:password@codeinsights-db:5432/postgres}
  sourcegraph-frontend-0:
    environment:
      - PGHOST=${MAIN_PGHOST:-pgsql}
      - PGPASSWORD=${MAIN_PGPASSWORD:-sg}

      - CODEINTEL_PGHOST=${CODEINTEL_PGHOST:-codeintel-db}
      - CODEINTEL_PGPASSWORD=${CODEINTEL_PGPASSWORD:-sg}

      - CODEINSIGHTS_PGDATASOURCE=${CODEINSIGHTS_PGDATASOURCE:-postgres://postgres:password@codeinsights-db:5432/postgres}

      - REDIS_STORE_ENDPOINT=${REDIS_STORE_ENDPOINT:-redis-store:6379}
      - REDIS_CACHE_ENDPOINT=${REDIS_CACHE_ENDPOINT:-redis-cache:6379}
  sourcegraph-frontend-internal:
    environment:
      - PGHOST=${MAIN_PGHOST:-pgsql}
      - PGPASSWORD=${MAIN_PGPASSWORD:-sg}

      - CODEINTEL_PGHOST=${CODEINTEL_PGHOST:-codeintel-db}
      - CODEINTEL_PGPASSWORD=${CODEINTEL_PGPASSWORD:-sg}

      - CODEINSIGHTS_PGDATASOURCE=${CODEINSIGHTS_PGDATASOURCE:-postgres://postgres:password@codeinsights-db:5432/postgres}

      - REDIS_STORE_ENDPOINT=${REDIS_STORE_ENDPOINT:-redis-store:6379}
      - REDIS_CACHE_ENDPOINT=${REDIS_CACHE_ENDPOINT:-redis-cache:6379}
